import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/ui/Footer/Footer'
import { CartProvider } from './components/context/CartContext'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {children}
          <Footer/>
          <ToastContainer />
        </CartProvider>
      </body>
    
    </html>
  )
}
