import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/ui/Footer/Footer'
import { CartProvider } from './components/context/CartContext'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from './components/context/AuthContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            {children}
            <Footer/>
            <ToastContainer />
          </CartProvider>
        </AuthProvider>
      </body>
    
    </html>
  )
}
